#!/bin/sh -ef
# Display a package's dependencies

pkg=${1:-"${PWD##*/}"}

spkg list "$pkg" >/dev/null || {
    printf 'usage: spkg-depends [pkg]\n' >&2
    exit 1
}

while read -r dep mak || [ "$dep" ]; do
    printf '%s%s\n' "$dep" "${mak:+ "$mak"}"
done 2>/dev/null < "$SPKG_ROOT/var/db/spkg/installed/$pkg/depends" 
