#!/bin/sh -ef
# Find the maintainer of a package

# Use the current directory as the package name if no package is given.
[ "$1" ] || {
    export SPKG_PATH="${PWD%/*}:$SPKG_PATH"
    set -- "${PWD##*/}"
}

spkg search "$@" | sort -u | while read -r repo; do cd "$repo"
    m=$(git log -1 --format='%an <%ae>' -- version 2>/dev/null) ||:

    [ "$m" ] || continue

    printf '=> %s\n%s\n' "$PWD" "$m"
done
